package routespec

// Document is the generated OpenAPI document.
type Document struct {
	OpenAPI    string              `json:"openapi"`
	Info       DocumentInfo        `json:"info"`
	Paths      map[string]PathItem `json:"paths"`
	Components Components          `json:"components,omitempty"`
}

// DocumentInfo contains the OpenAPI info object.
type DocumentInfo struct {
	Title       string `json:"title"`
	Version     string `json:"version"`
	Description string `json:"description,omitempty"`
}

// Components holds reusable schemas.
type Components struct {
	Schemas         map[string]Schema         `json:"schemas,omitempty"`
	SecuritySchemes map[string]SecurityScheme `json:"securitySchemes,omitempty"`
}

// PathItem holds operations for one path.
type PathItem struct {
	Get     *DocumentOperation `json:"get,omitempty"`
	Put     *DocumentOperation `json:"put,omitempty"`
	Post    *DocumentOperation `json:"post,omitempty"`
	Delete  *DocumentOperation `json:"delete,omitempty"`
	Patch   *DocumentOperation `json:"patch,omitempty"`
	Head    *DocumentOperation `json:"head,omitempty"`
	Options *DocumentOperation `json:"options,omitempty"`
	Trace   *DocumentOperation `json:"trace,omitempty"`
}

// DocumentOperation is an OpenAPI operation.
type DocumentOperation struct {
	OperationID string                `json:"operationId,omitempty"`
	Summary     string                `json:"summary,omitempty"`
	Description string                `json:"description,omitempty"`
	Tags        []string              `json:"tags,omitempty"`
	Security    []SecurityRequirement `json:"security,omitempty"`
	Parameters  []Parameter           `json:"parameters,omitempty"`
	RequestBody *RequestBody          `json:"requestBody,omitempty"`
	Responses   map[string]Response   `json:"responses"`
}

// Parameter is an OpenAPI path or query parameter.
type Parameter struct {
	Name        string `json:"name"`
	In          string `json:"in"`
	Description string `json:"description,omitempty"`
	Required    bool   `json:"required,omitempty"`
	Schema      Schema `json:"schema"`
}

// RequestBody is an OpenAPI request body.
type RequestBody struct {
	Required bool                 `json:"required"`
	Content  map[string]MediaType `json:"content"`
}

// Response is an OpenAPI response.
type Response struct {
	Description string               `json:"description"`
	Content     map[string]MediaType `json:"content,omitempty"`
}

// MediaType describes a representation schema.
type MediaType struct {
	Schema Schema `json:"schema"`
}

// Schema is the subset of OpenAPI 3.1 Schema Objects generated by routespec.
type Schema struct {
	Ref                  string            `json:"$ref,omitempty"`
	Type                 string            `json:"type,omitempty"`
	Format               string            `json:"format,omitempty"`
	Description          string            `json:"description,omitempty"`
	Default              any               `json:"default,omitempty"`
	Example              any               `json:"example,omitempty"`
	Enum                 []any             `json:"enum,omitempty"`
	ReadOnly             bool              `json:"readOnly,omitempty"`
	WriteOnly            bool              `json:"writeOnly,omitempty"`
	Deprecated           bool              `json:"deprecated,omitempty"`
	MinLength            *int              `json:"minLength,omitempty"`
	MaxLength            *int              `json:"maxLength,omitempty"`
	Pattern              string            `json:"pattern,omitempty"`
	Minimum              *float64          `json:"minimum,omitempty"`
	Maximum              *float64          `json:"maximum,omitempty"`
	MultipleOf           *float64          `json:"multipleOf,omitempty"`
	MinItems             *int              `json:"minItems,omitempty"`
	MaxItems             *int              `json:"maxItems,omitempty"`
	MinProperties        *int              `json:"minProperties,omitempty"`
	MaxProperties        *int              `json:"maxProperties,omitempty"`
	OneOf                []Schema          `json:"oneOf,omitempty"`
	Properties           map[string]Schema `json:"properties,omitempty"`
	Required             []string          `json:"required,omitempty"`
	Items                *Schema           `json:"items,omitempty"`
	AdditionalProperties *Schema           `json:"additionalProperties,omitempty"`
}
